INSERT INTO categorias(titulo, cor) VALUES ('Livre', '#1C1C1C');
INSERT INTO categorias(titulo, cor) VALUES ('Carreira', '#0000FF');
INSERT INTO categorias(titulo, cor) VALUES ('Estudos', '#008000');

INSERT INTO videos(titulo, descricao, url, categoria_id) VALUES('O que são Git e Github?', 'Veja como funcionam as mais famosas e utilizadas ferramentas de colaboração no universo da Tecnologia e tenha controle sob as versões diferentes de seus projetos.', 'https://www.youtube.com/watch?v=P4BNi_yPehc&list=PLh2Y_pKOa4UciHMCIdxq96xX_L0gX2rYg&ab_channel=AluraCursosOnline',1);
INSERT INTO videos(titulo, descricao, url, categoria_id) VALUES('Diferença entre Back-End e Front-End com Mario Souto', 'Qual a diferença entre Back-end e Front-end? É possível se especializar nas duas áreas? Como é a rotina desses profissionais e com quais outras áreas da tecnologia acabam se relacionando?', 'https://www.youtube.com/watch?v=xrRy3RI3HE4&list=PLh2Y_pKOa4Ufs_KwjTdGBFH6b65ChApyD&index=6&ab_channel=AluraCursosOnline',2);
INSERT INTO videos(titulo, descricao, url, categoria_id) VALUES('O que faz uma desenvolvedora Back-end? com Juliana Amoasei', 'Afinal, quem trabalha com Back-end faz o que? Com quais outras áreas da tecnologia essa pessoa acaba se relacionando no dia a dia de trabalho e quais os possíveis caminhos nessa carreira?', 'https://www.youtube.com/watch?v=fiPfvylj6rk&list=PLh2Y_pKOa4Ufs_KwjTdGBFH6b65ChApyD&index=14&ab_channel=AluraCursosOnline',2);
INSERT INTO videos(titulo, descricao, url, categoria_id) VALUES('Clean Code e Solid com Alberto Sousa, o Dev Eficiente', 'Trabalhando com desenvolvimento de software, muito provavelmente você já ouviu falar de Clean Code e Solid. Mas, será que essas práticas devem, obrigatoriamente, ser seguidas à risca para desenvolver um bom projeto?', 'https://www.youtube.com/watch?v=XV9B4LX_re8&list=PLh2Y_pKOa4Ufs_KwjTdGBFH6b65ChApyD&index=15&ab_channel=AluraCursosOnline',3);
INSERT INTO videos(titulo, descricao, url, categoria_id) VALUES('Containers, Docker e Kubernetes com Giovanni Bassi', 'O uso de Containers e de plataformas Open Sources como Docker e Kubernetes são cada vez mais usadas no universo tech. Você sabe como eles funcionam?', 'https://www.youtube.com/watch?v=wxLvvMxzc1Q&list=PLh2Y_pKOa4Ufs_KwjTdGBFH6b65ChApyD&ab_channel=AluraCursosOnline',3);
